apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    chart: {{ template "web-app-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.backend.type }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backend
    release: {{ .Release.Name }}
