apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    chart: {{ template "web-app-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.type }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
    release: {{ .Release.Name }}
