# Default values for web-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

appImage:
  repository: mmilja/webapp
  backend: back-end-%WEB_APP_VERSION%
  frontend: front-end-%WEB_APP_VERSION%
  pullPolicy: IfNotPresent

backend:
  type: ClusterIP
  port: 80

frontend:
  type: ClusterIP
  port: 80

appResources: {}

appNodeSelector: {}

appTolerations: []

appAffinity: {}
